name: Build and run tests

on:
  pull_request:

jobs:
  BuildAndTest:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v1
      
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0'

      - name: Cache Swift packages
        uses: actions/cache@v2
        with:
          path: |
              .build/checkouts
              .build/repositories
              .build/workspace-state.json
          key: ${{ runner.os }}-${{ hashFiles('Package.resolved') }}

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
